on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.20.0
        with:
          classpath: 'example/changelogs/ojdbc8.jar'
          defaultSchemaName: LIQUIBASE
          liquibaseSchemaName: LIQUIBASE
          changeLogFile: 'example/changelogs/changelog.oracle.sql'
          username: 'system'
          password: 'oracle'
          url: 'jdbc:oracle:thin:@100.26.138.199:1521/xe?oracle.jdbc.timezoneAsRegion=false'
        

