on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs/ojdbc8.jar'
          changeLogFile: 'example/changelogs/changelog.oracle.sql'
          username: 'system'
          password: 'oracle'
          url: 'jdbc:oracle:thin:@100.26.138.199:1521/xe'
          liquibaseSchemaName: LIQUIBASE
